### ISSUE TITLE
Cannot add via Swift Packages

### ISSUE THREAD

**Issue by ritesh-kanchi** [sanity-io/swift-sanity#13]
When adding 0.3.0 via Swift Packages to a project, the follow error appears due to the Package Resolution Failing:

`Dependencies could not be resolved because package 'swift-sanity' is required using a stable-version but 'swift-sanity' depends on an unstable-version package 'eventsource' and root depends on 'swift-sanity' 0.3.0.`

**Comment by sgulseth** [comment]
Hi, thanks for reporting! Looks like this is caused by us depending on a non-semver version. I'll look into this and see if I can find a way around it, meanwhile it should work if you depend on the commit hash instead of a semver range:

![image](https://user-images.githubusercontent.com/1627633/124783473-62e75f80-df45-11eb-8d15-e3cb21b44de0.png)
